[package]
name = "witgen"
version = "0.1.0"
edition = "2021"
authors = ["Benjamin Coenen <benjamin.coenen@hotmail.com>"]
description = "witgen is a library to help you generate wit definitions in a wit file for WebAssembly"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/bnjjj/witgen"
keywords = ["webassembly", "generate", "cargo", "wasm"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
witgen_macro = { path = "crates/witgen_macro" }

[workspace]
members = ["crates/witgen_macro", "crates/cargo_witgen"]
