[package]
name = "cargo-witgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.51"
cargo_metadata = "0.14.1"
clap = "2.34.0"
glob = "0.3.0"
once_cell = "1.8.0"
